# Generated by Django 6.0.3 on 2026-03-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jersey'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='back_image',
            field=models.ImageField(default=1, upload_to='jerseys/'),
            preserve_default=False,
        ),
    ]
