# Generated by Django 6.0.3 on 2026-03-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_jersey_back_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jersey',
            old_name='back_image',
            new_name='img2',
        ),
        migrations.AddField(
            model_name='jersey',
            name='img10',
            field=models.ImageField(blank=True, null=True, upload_to='jerseys/'),
        ),
        migrations.AddField(
            model_name='jersey',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='jersey/'),
        ),
        migrations.AddField(
            model_name='jersey',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='jerseys/'),
        ),
        migrations.AddField(
            model_name='jersey',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='jerseys/'),
        ),
        migrations.AddField(
            model_name='jersey',
            name='img6',
            field=models.ImageField(blank=True, null=True, upload_to='jerseys/'),
        ),
        migrations.AddField(
            model_name='jersey',
            name='img7',
            field=models.ImageField(blank=True, null=True, upload_to='jerseys/'),
        ),
        migrations.AddField(
            model_name='jersey',
            name='img8',
            field=models.ImageField(blank=True, null=True, upload_to='jerseys/'),
        ),
        migrations.AddField(
            model_name='jersey',
            name='img9',
            field=models.ImageField(blank=True, null=True, upload_to='jerseys/'),
        ),
    ]
