# Generated by Django 6.0.3 on 2026-03-06 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_back_image_jersey_img2_jersey_img10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='category',
            field=models.CharField(choices=[('club', 'Club Jersey'), ('worldcup', 'World Cup Jersey')], default='General', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jersey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
