# Generated by Django 6.0.3 on 2026-03-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_jersey_category_jersey_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
