# Generated by Django 6.0.3 on 2026-03-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_whislist_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='jersey',
            name='players',
            field=models.TextField(blank=True),
        ),
    ]
