# Generated by Django 6.0.3 on 2026-03-11 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='JerseySize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=5)),
                ('stock', models.IntegerField(default=0)),
                ('jersey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='app.jersey')),
            ],
        ),
    ]
