# Generated by Django 6.0.3 on 2026-03-11 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_jerseysize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jersey',
            name='stock',
        ),
    ]
