# Generated by Django 6.0.3 on 2026-03-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_jersey_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='custom_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
