# Generated by Django 6.0.3 on 2026-03-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_cart_custom_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default=2, max_length=5),
            preserve_default=False,
        ),
    ]
