# Generated by Django 6.0.3 on 2026-03-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cart_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='custom_text',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='size',
        ),
        migrations.AddField(
            model_name='cart',
            name='player_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='player_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
