# Generated by Django 6.0.3 on 2026-03-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_cart_custom_text_remove_cart_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='size',
            field=models.CharField(default='M', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='player_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='player_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
