# Generated by Django 6.0.3 on 2026-03-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_chatmessage_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('team', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
